set_property PACKAGE_PIN Y14 [get_ports {led[1]}]
set_property PACKAGE_PIN AA13 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN W17 [get_ports sys_clk]
set_property PACKAGE_PIN V4 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
