# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/GPIO_KEY.xdc

# Block Designs: bd/gpio_key/gpio_key.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_key || ORIG_REF_NAME==gpio_key} -quiet] -quiet

# IP: bd/gpio_key/ip/gpio_key_processing_system7_0_0/gpio_key_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_key_processing_system7_0_0 || ORIG_REF_NAME==gpio_key_processing_system7_0_0} -quiet] -quiet

# XDC: bd/gpio_key/gpio_key_ooc.xdc
