set_property SRC_FILE_INFO {cfile:D:/ZynqProject/ip_fifo/ip_fifo.srcs/constrs_1/new/ip_fifo.xdc rfile:../../../ip_fifo.srcs/constrs_1/new/ip_fifo.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W17 [get_ports sys_clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports sys_rst_n]
